config/routes.rb
Rails.application.routes.draw do
  resources :docentes
  resources :derivacions
  resources :entrevista
  resources :departamentos
  resources :aulas
  resources :motivos
  resources :horarios
  resources :alumnos

end

app/models/motivo.rb
class Motivo < ActiveRecord::Base
	has_many :entrevista
end

app/controllers/motivos_controller.rb
class MotivosController < ApplicationController
  before_action :set_motivo, only: [:show, :edit, :update, :destroy]

  # GET /motivos
  # GET /motivos.json
  def index
    @motivos = Motivo.all
  end

  # GET /motivos/1
  # GET /motivos/1.json
  def show
  end

  # GET /motivos/new
  def new
    @motivo = Motivo.new
  end

  # GET /motivos/1/edit
  def edit
  end

  # POST /motivos
  # POST /motivos.json
  def create
    @motivo = Motivo.new(motivo_params)

    respond_to do |format|
      if @motivo.save
        format.html { redirect_to @motivo, notice: 'Motivo was successfully created.' }
        format.json { render :show, status: :created, location: @motivo }
      else
        format.html { render :new }
        format.json { render json: @motivo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /motivos/1
  # PATCH/PUT /motivos/1.json
  def update
    respond_to do |format|
      if @motivo.update(motivo_params)
        format.html { redirect_to @motivo, notice: 'Motivo was successfully updated.' }
        format.json { render :show, status: :ok, location: @motivo }
      else
        format.html { render :edit }
        format.json { render json: @motivo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /motivos/1
  # DELETE /motivos/1.json
  def destroy
    @motivo.destroy
    respond_to do |format|
      format.html { redirect_to motivos_url, notice: 'Motivo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_motivo
      @motivo = Motivo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def motivo_params
      params.require(:motivo).permit(:tipo)
    end
end

app/helpers/motivos_helper.rb
module MotivosHelper
end

app/views/motivos/_form.html.erb
<%= form_for(@motivo) do |f| %>
  <% if @motivo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@motivo.errors.count, "error") %> prohibited this motivo from being saved:</h2>

      <ul>
      <% @motivo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tipo %><br>
    <%= f.text_field :tipo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/motivos/edit.html.erb
<h1>Editing Motivo</h1>

<%= render 'form' %>

<%= link_to 'Show', @motivo %> |
<%= link_to 'Back', motivos_path %>

app/views/motivos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Motivos</h1>

<table>
  <thead>
    <tr>
      <th>Tipo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @motivos.each do |motivo| %>
      <tr>
        <td><%= motivo.tipo %></td>
        <td><%= link_to 'Show', motivo %></td>
        <td><%= link_to 'Edit', edit_motivo_path(motivo) %></td>
        <td><%= link_to 'Destroy', motivo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Motivo', new_motivo_path %>

app/views/motivos/new.html.erb
<h1>New Motivo</h1>

<%= render 'form' %>

<%= link_to 'Back', motivos_path %>

app/views/motivos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tipo:</strong>
  <%= @motivo.tipo %>
</p>

<%= link_to 'Edit', edit_motivo_path(@motivo) %> |
<%= link_to 'Back', motivos_path %>