config/routes.rb
Rails.application.routes.draw do
  resources :docentes
  resources :derivacions
  resources :entrevista
  resources :departamentos
  resources :aulas
  resources :motivos
  resources :horarios
  resources :alumnos

end

app/models/docente.rb
class Docente < ActiveRecord::Base
	has_many :horarios
end

app/controllers/docentes_controller.rb
class DocentesController < ApplicationController
  before_action :set_docente, only: [:show, :edit, :update, :destroy]

  # GET /docentes
  # GET /docentes.json
  def index
    @docentes = Docente.all
  end

  # GET /docentes/1
  # GET /docentes/1.json
  def show
  end

  # GET /docentes/new
  def new
    @docente = Docente.new
  end

  # GET /docentes/1/edit
  def edit
  end

  # POST /docentes
  # POST /docentes.json
  def create
    @docente = Docente.new(docente_params)

    respond_to do |format|
      if @docente.save
        format.html { redirect_to @docente, notice: 'Docente was successfully created.' }
        format.json { render :show, status: :created, location: @docente }
      else
        format.html { render :new }
        format.json { render json: @docente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /docentes/1
  # PATCH/PUT /docentes/1.json
  def update
    respond_to do |format|
      if @docente.update(docente_params)
        format.html { redirect_to @docente, notice: 'Docente was successfully updated.' }
        format.json { render :show, status: :ok, location: @docente }
      else
        format.html { render :edit }
        format.json { render json: @docente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /docentes/1
  # DELETE /docentes/1.json
  def destroy
    @docente.destroy
    respond_to do |format|
      format.html { redirect_to docentes_url, notice: 'Docente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_docente
      @docente = Docente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def docente_params
      params.require(:docente).permit(:nropeople, :apellido, :nombre, :emailuap, :sexo, :fechancimiento, :carrera, :añolectivo)
    end
end

app/helpers/docentes_helper.rb
module DocentesHelper
end

app/views/docentes/_form.html.erb
<%= form_for(@docente) do |f| %>
  <% if @docente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@docente.errors.count, "error") %> prohibited this docente from being saved:</h2>

      <ul>
      <% @docente.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nropeople %><br>
    <%= f.number_field :nropeople %>
  </div>
  <div class="field">
    <%= f.label :apellido %><br>
    <%= f.text_field :apellido %>
  </div>
  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :emailuap %><br>
    <%= f.text_field :emailuap %>
  </div>
  <div class="field">
    <%= f.label :sexo %><br>
    <%= f.check_box :sexo %>
  </div>
  <div class="field">
    <%= f.label :fechancimiento %><br>
    <%= f.date_select :fechancimiento %>
  </div>
  <div class="field">
    <%= f.label :carrera %><br>
    <%= f.text_field :carrera %>
  </div>
  <div class="field">
    <%= f.label :añolectivo %><br>
    <%= f.date_select :añolectivo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/docentes/edit.html.erb
<h1>Editing Docente</h1>

<%= render 'form' %>

<%= link_to 'Show', @docente %> |
<%= link_to 'Back', docentes_path %>

app/views/docentes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Docentes</h1>

<table>
  <thead>
    <tr>
      <th>Nropeople</th>
      <th>Apellido</th>
      <th>Nombre</th>
      <th>Emailuap</th>
      <th>Sexo</th>
      <th>Fechancimiento</th>
      <th>Carrera</th>
      <th>Añolectivo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @docentes.each do |docente| %>
      <tr>
        <td><%= docente.nropeople %></td>
        <td><%= docente.apellido %></td>
        <td><%= docente.nombre %></td>
        <td><%= docente.emailuap %></td>
        <td><%= docente.sexo %></td>
        <td><%= docente.fechancimiento %></td>
        <td><%= docente.carrera %></td>
        <td><%= docente.añolectivo %></td>
        <td><%= link_to 'Show', docente %></td>
        <td><%= link_to 'Edit', edit_docente_path(docente) %></td>
        <td><%= link_to 'Destroy', docente, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Docente', new_docente_path %>

app/views/docentes/new.html.erb
<h1>New Docente</h1>

<%= render 'form' %>

<%= link_to 'Back', docentes_path %>

app/views/docentes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nropeople:</strong>
  <%= @docente.nropeople %>
</p>

<p>
  <strong>Apellido:</strong>
  <%= @docente.apellido %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @docente.nombre %>
</p>

<p>
  <strong>Emailuap:</strong>
  <%= @docente.emailuap %>
</p>

<p>
  <strong>Sexo:</strong>
  <%= @docente.sexo %>
</p>

<p>
  <strong>Fechancimiento:</strong>
  <%= @docente.fechancimiento %>
</p>

<p>
  <strong>Carrera:</strong>
  <%= @docente.carrera %>
</p>

<p>
  <strong>Añolectivo:</strong>
  <%= @docente.añolectivo %>
</p>

<%= link_to 'Edit', edit_docente_path(@docente) %> |
<%= link_to 'Back', docentes_path %>